/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CrearClases.java
 *
 * Created on 22/07/2009, 10:50:52 AM
 */

package interfaz;

import interfacebd.InterfaceBD;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import manejadores.mnjListaTablas;
import utilerias.Procedimientos;
import utilerias.VariablesGlobales;

/**
 *
 * @author zeus
 */
public class CrearClases extends javax.swing.JFrame {
    InterfaceBD bd;

    /** Creates new form CrearClases */
    public CrearClases() {
        initComponents();
        CrearClases.pbBarra.setVisible(false);
    }

    public CrearClases(InterfaceBD bd) {
        this();
        this.bd = bd;
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txCarpetaDestino = new javax.swing.JTextField();
        btExaminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txPaqClases = new javax.swing.JTextField();
        txPaqClaseTabla = new javax.swing.JTextField();
        btSiguiente = new javax.swing.JButton();
        btRegresar = new javax.swing.JButton();
        pbBarra = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear Clases");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Carpeta destino:");

        txCarpetaDestino.setEditable(false);

        btExaminar.setText("Examinar");
        btExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExaminarActionPerformed(evt);
            }
        });

        jLabel2.setText("Paquete clases:");

        jLabel3.setText("Paquete clase Tabla:");

        txPaqClaseTabla.setText("Utilerias");
        txPaqClaseTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPaqClaseTablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txCarpetaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btExaminar, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                            .addComponent(txPaqClases, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txPaqClaseTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txCarpetaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExaminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txPaqClases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txPaqClaseTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btSiguiente.setFont(new java.awt.Font("Tahoma", 0, 10));
        btSiguiente.setText("Crear");
        btSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSiguienteActionPerformed(evt);
            }
        });

        btRegresar.setFont(new java.awt.Font("Tahoma", 0, 10));
        btRegresar.setText("<Regresar");
        btRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pbBarra, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                        .addComponent(btSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRegresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegresarActionPerformed
        this.dispose();
        new SeleccionProceso(bd);
    }//GEN-LAST:event_btRegresarActionPerformed

    private void btExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExaminarActionPerformed
        JFileChooser seleccionar = new JFileChooser();
        seleccionar.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        File rutaDir = null;
        if(!txCarpetaDestino.getText().equals("")){
            rutaDir = new File(txCarpetaDestino.getText().replace("\\", "\\\\"));
        }else if(new File("C:\\ARCHIVOS DE LUIS\\Archivos y documentos de LUIS\\NetBeans Projects\\").exists()){
            rutaDir = new File("C:\\ARCHIVOS DE LUIS\\Archivos y documentos de LUIS\\NetBeans Projects\\");
        }
        seleccionar.setCurrentDirectory(rutaDir);
        if(seleccionar.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            this.txCarpetaDestino.setText(seleccionar.getSelectedFile().getAbsolutePath());
            String paqueteClases = "";
            String [] elementos = seleccionar.getSelectedFile().getAbsolutePath().split("\\\\");
            if(elementos.length>=3){
                paqueteClases = elementos[elementos.length-3]+"."+elementos[elementos.length-2]+"."+elementos[elementos.length-1];
            }
            this.txPaqClases.setText(paqueteClases);
            String ruta = txCarpetaDestino.getText().replace("\\", "\\\\");
            VariablesGlobales.setRutaDestino(ruta);
        }
    }//GEN-LAST:event_btExaminarActionPerformed

    private void btSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSiguienteActionPerformed
        if(validaciones()){
            VariablesGlobales.setPaqClaseTabla(txPaqClaseTabla.getText());
            VariablesGlobales.setPaqClases(txPaqClases.getText());
            Procedimientos proc = new Procedimientos(VariablesGlobales.getTablas());
            Thread hilo = new Thread(proc);
            hilo.start();
        }
    }//GEN-LAST:event_btSiguienteActionPerformed

    private void txPaqClaseTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPaqClaseTablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPaqClaseTablaActionPerformed

    public boolean validaciones(){
       boolean valido = true;
       if(txCarpetaDestino.getText().equals("")){
            JOptionPane.showMessageDialog(this, "No has elegido la carpeta destino.");
            btExaminar.doClick();
            valido = false;
        }else if(txPaqClaseTabla.getText().equals("")){
            JOptionPane.showMessageDialog(this, "No has escrito el paquete de la clase 'Tabla'.");
            txPaqClaseTabla.requestFocusInWindow();
            valido = false;
        }else if(txPaqClases.getText().equals("")){
            JOptionPane.showMessageDialog(this, "No has escrito el paquete de las clases a crear.");
            txPaqClases.requestFocusInWindow();
            valido = false;
        }
       return valido;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExaminar;
    private javax.swing.JButton btRegresar;
    private javax.swing.JButton btSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JProgressBar pbBarra;
    private javax.swing.JTextField txCarpetaDestino;
    private javax.swing.JTextField txPaqClaseTabla;
    private javax.swing.JTextField txPaqClases;
    // End of variables declaration//GEN-END:variables

}
