/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SeleccionProceso.java
 *
 * Created on 23/07/2009, 12:39:25 PM
 */

package interfaz;

import interfacebd.InterfaceBD;
import manejadores.mnjListaCampos;
import manejadores.mnjListaTablas;

/**
 *
 * @author zeus
 */
public class SeleccionProceso extends javax.swing.JFrame {

    InterfaceBD bd;

    /** Creates new form SeleccionProceso */
    public SeleccionProceso(InterfaceBD bd) {
        this.bd = bd;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgrp = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rdClases = new javax.swing.JRadioButton();
        rdFormularios = new javax.swing.JRadioButton();
        rdSecuencias = new javax.swing.JRadioButton();
        btRegresar = new javax.swing.JButton();
        btSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Procedimiento");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccionar procedimiento"));

        btgrp.add(rdClases);
        rdClases.setText("Generar clases Java");
        rdClases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdClasesActionPerformed(evt);
            }
        });

        btgrp.add(rdFormularios);
        rdFormularios.setText("Generar formularios (JSP's)");
        rdFormularios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFormulariosActionPerformed(evt);
            }
        });

        btgrp.add(rdSecuencias);
        rdSecuencias.setText("Generar Secuencias");
        rdSecuencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdSecuenciasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rdClases)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdFormularios))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(rdSecuencias)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdClases)
                    .addComponent(rdFormularios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdSecuencias))
        );

        btRegresar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btRegresar.setText("<Regresar");
        btRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegresarActionPerformed(evt);
            }
        });

        btSiguiente.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btSiguiente.setText("Siguiente>");
        btSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(btSiguiente)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSiguiente)
                    .addComponent(btRegresar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdClasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdClasesActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_rdClasesActionPerformed

    private void rdFormulariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFormulariosActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_rdFormulariosActionPerformed

    private void btSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSiguienteActionPerformed
        if(rdClases.isSelected()){
            new CrearClases(bd);
        }else if(rdSecuencias.isSelected()){
            new CrearSecuencias(bd);
        }else{
            new mnjListaCampos(bd);
        }
        this.dispose();
    }//GEN-LAST:event_btSiguienteActionPerformed

    private void btRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegresarActionPerformed
        this.dispose();
        new mnjListaTablas(bd);
    }//GEN-LAST:event_btRegresarActionPerformed

    private void rdSecuenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdSecuenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdSecuenciasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegresar;
    private javax.swing.JButton btSiguiente;
    private javax.swing.ButtonGroup btgrp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdClases;
    private javax.swing.JRadioButton rdFormularios;
    private javax.swing.JRadioButton rdSecuencias;
    // End of variables declaration//GEN-END:variables

}
